worker_processes auto;

events {
    worker_connections 1024;
}

http
{
    include mime.types;

    upstream verdictio-server {
        least_conn;
        server server:8000;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certificates/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certificates/nginx-selfsigned.key;
        
		location / {
            proxy_pass http://verdictio-server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}